### PR TITLE
chain: attempt to reconnect zmq to bitcoind after disconnection

### PR DESCRIPTION
**Pull request by aakselrod**
This PR enables ZMQ reconnection for the bitcoind back-end.

### CODE REVIEW

**Comment by Roasbeef** [comment]
Hmm, should this instead be at the `zmq` level? As in the wallet keeps reading as normal, but it's the `zmq` lib below that'll actually handle the reconnects itself.

**Comment by aakselrod** [comment]
It worked out a bit easier to do in `btcwallet` because I couldn't really see how to do it at the `zmq` level but I think I have an idea. Let me try it out.

**Comment by aakselrod** [comment]
Underlying ZMQ library PR submitted at https://github.com/lightninglabs/gozmq/pull/2 - the disadvantage of that one is we don't get logs when we disconnect and reconnect, but we still get logs when RPC calls fail, so it shouldn't be a huge deal.

**Comment by aakselrod** [comment]
This can be closed as the problem is solved in the underlying ZMQ library. Reconnects to RPC where the cookie changes out from under the client will take a larger refactor of the connection configuration.

**Pull request closed without merging**
